### ISSUE TITLE
Withings changed authentication to OAuth 2.0 - sync broken

### ISSUE THREAD

**Issue by rafdev18** [jaroslawhartman/withings-garmin-v2#10]
Our friends at Withings changed the authentication protocol from OAuth 1.0 towards 2.0 and switched off on November 30th. Now the sync with the scale is broken - 

Any chance to update the code to OAuth 2.0 ? Thanks for your help !

**Comment by jaroslawhartman** [comment]
Thanks for reporting... 

I need to review but reading new API requires to register the app at Withings/Nokia - not sure if they agree for this.

As for now, I'm not very optimistic ☹️

**Comment by jaroslawhartman** [comment]
Hi @rafdev18 
I believe it has been fixed as 6e88b6e2c91dfb1172fb728343e28b5b647753ae .

Would it be possible from your side to verify?

Thank you,
Jarek

PS: I'm closing this ticket for now but feel free to post here or in an other ticket.
