### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group' again

### ISSUE THREAD

**Issue by obsqre** [jaroslawhartman/withings-garmin-v2#13]
Hi
I just started using this, and it worked like a charm. 
It seems an issue earlier refered to in #2 and #4 has reemerged - same error reported.
The search for username in the page returned by session.get does not seem to contain the texxt searched for in this line from login() in garmin.py
`userdata_json_str = re.search(r"VIEWER_SOCIAL_PROFILE\s*=\s*JSON\.parse\((.+)\);$", dashboard.text, re.MULTILINE).group(1)`  
The dashboard.text is a web page containing some java scrips, that also seems to contain comments on how to log in. 
It does seem the login is performed ok though. It is just that the page returned by get_session is not the expected one.

**Comment by jaroslawhartman** [comment]
Hi, confirming this issue.

Will take a look.

**Comment by jaroslawhartman** [comment]
Please get the latest version - the problem seems fixed there.

Thank you,
Jarek

**Comment by The-Compiler** [comment]
Yay, seems to work fine - thanks for the fix! :heart:

**Comment by obsqre** [comment]
Yes! Works! Thank you very much, highly appreciated!
