### ISSUE TITLE
Sync last month

### ISSUE THREAD

**Issue by buchholzs** [jaroslawhartman/withings-garmin-v2#14]
Would be nice if you could specifiy to sync the last month only instead of a fixed date.

**Comment by matthewnessworthy** [comment]
depending on your operating system you can just pass in a command for last month

MACOS
```
./sync --fromdate=$(date -v-1m +%F)
```

*UNIX
```
./sync --fromdate=$(date --date="1 month ago")
```

**Comment by buchholzs** [comment]
I am using Windows 10. However, in the mean time I wrote a batch file myself. It is here: https://github.com/buchholzs/withings-garmin-task

**Comment by jaroslawhartman** [comment]
> I am using Windows 10. However, in the mean time I wrote a batch file myself. It is here: https://github.com/buchholzs/withings-garmin-task

Good stuff! Let me promote it in the README.

**Comment by jaroslawhartman** [comment]
> depending on your operating system you can just pass in a command for last month
> 
> MACOS
> 
> ```
> ./sync --fromdate=$(date -v-1m +%F)
> ```
> 
> *UNIX
> 
> ```
> ./sync --fromdate=$(date --date="1 month ago")
> ```

This is worth promoting as well, thank you.
