### ISSUE TITLE
Support for calculated BMI values

### ISSUE THREAD

**Issue by chriselsen** [jaroslawhartman/withings-garmin-v2#16]
Would be great to get calculated BMI values into Garmin.

Here is a link to some more information including code from a similar project:
https://github.com/magnific0/nokia-weight-sync/pull/13

**Comment by rcork** [comment]
@chriselsen i see calculated BMI when i look at the Garmin Connect on the web. However, when i look in the Connect app for iOS, it doesn't have BMI. It must be calculating the BMI from the weight data along with my height set on the profile.

**Comment by chriselsen** [comment]
@rcork Yes, have a look at the referenced link for more details. 
From what I understand in a nutshell:
Gamin Connect on the web calculates in the fly the BMI value, which neither the iOS nor the Android app of Connect can do. 
To "fix" this for good you can calculate the BMI at import and include it in the imported FIT file. That way the imported results simulate a Garmin scale, which does have BMI (and other data built-in) and then stores that inside the FIT file. 
Have look at https://github.com/magnific0/nokia-weight-sync/pull/13/files for details on BMI in the FIT file.

**Comment by rcork** [comment]
@chriselsen i played around with the code this morning and was able to get it to calculate and send in the BMI In the FIT upload and it’s showing in the iOS app. Ill submit a pull request but since the developer doesn’t seem to be maintaining this project, I may just fork it with my changes.

**Comment by rcork** [comment]
@chriselsen i created a pull request with the changes to calculate BMI. If you want to try it out before it gets merged here, you can get it in my fork. https://github.com/rcork/withings-garmin-v2

**Comment by chriselsen** [comment]
Thanks! Works like a charm for me. Build a [docker image](https://hub.docker.com/r/chriselsen/withings-garmin) based on your change and used that.
