### ISSUE TITLE
persistent docker container + docker-compose

### ISSUE THREAD

**Issue by zakaszewski** [jaroslawhartman/withings-garmin-v2#17]
Hi,

first of all thank You very much for your work! I have a few questions:

1) Is there a way to make the script/tool run as a continuous/persistent docker daemon?
Currently, I'm only able to manually run the container via
`docker start -i withings`
which then automatically terminates after syncing data (to garmin connect, in my case). That way, I need to re-run the container after each weighing, or alternatively add a cronjob to do this regularly. I'd prefer to have the container running all the time and continuously sync new weight data, is there something I'm missing or is this not possible?

2) Does anyone have a clue if/how to include this script in a docker-compose.yml? Also, any idea on how to include a host volume for the script's config (in order to allow for central storage and ultimately, backup of all relevant config data)?

Best regards,
Piotr

**Comment by modelstudent101** [comment]
I think based off of the way it's written, you would need to alter the container to continually run it and it would need to ping the Withings server constantly in order to upload in real time or, alternatively, to sync every x amount of minutes/hours/etc, which would, in effect, be the same yet more resource intensive than the cronjob.

**Comment by stynoo** [comment]
I got two instances of [this](https://github.com/stynoo/docker-withings-sync) running 24/7 dockerized on a Synology nas.  It ran flawless for a couple of months till Garmigeddon hit last week.

**Comment by rcork** [comment]
> I got two instances of [this](https://github.com/stynoo/docker-withings-sync) running 24/7 dockerized on a Synology nas. It ran flawless for a couple of months till Garmigeddon hit last week.

@stynoo How did you pass in the garmin username and password when setting up on Synology. I created the container in DSM and set GARMIN_USERNAME and GARMIN_PASSWORD in the Environment Variables. I then ssh'd into the Synology and ran docker start -i to get an interactive shell so i could paste the OAuth code back into the shell but it say Garmin username is missing. I then went back into DSM and clicked start on the container and it runs and pulls the data from Withings but still complains of no Garmin username so it wont upload.

**Comment by stynoo** [comment]
@rcork Iirc I ran it once manually from command line from the docker shell to let it create the appropriate config files.  Then copied over those files to a directory that is mounted within the docker instance itself. 
The garmin username & passwords are then provided from shell (crontab)
