### ISSUE TITLE
Thank you - Still something strange

### ISSUE THREAD

**Issue by agentbond007** [jaroslawhartman/withings-garmin-v2#3]
First, Thank you.  I updated garmin.py and I'm still receiving the following 

Traceback (most recent call last):
  File "sync.py", line 125, in <module>
    main()
  File "sync.py", line 60, in main
    sync(**opts.__dict__)
  File "sync.py", line 117, in sync
    cookie = garmin.login(garmin_username, garmin_password)
  File "/1-CODE/PYTHON/Withings-Garmin/garmin.py", line 132, in login
    cookies = self._get_cookies(email=username, password=password)
  File "/1-CODE/PYTHON/Withings-Garmin/garmin.py", line 100, in _get_cookies
    data["lt"] = re.search("name=\"lt\"\s+value=\"([^\"]+)\"", preResp.text).groups(1)[0]
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by jaroslawhartman** [comment]
Please note that also the sync.py has been changed to retrieve and use _session_ variable (and no longer _cookies_).

```
    session = garmin.login(garmin_username, garmin_password)
    verbose_print('attempting to upload fit file...\n')
    r = garmin.upload_file(fit.getvalue(), session)
```

**Comment by agentbond007** [comment]
So Cool Jarek.  I learned how to sync an upstream fork in git.  I had forked your repo and then I did a sync and merge upstream. I resolved the conflicts I had with garmin.py and sync.py in local remote. I then ran sync.py and the data imported into Garmin from Withings.  Awesome.   Thank you.

**Comment by jaroslawhartman** [comment]
Good too hear it's being solved!
