### ISSUE TITLE
user has not opened withings data

### ISSUE THREAD

**Issue by pelicangris** [jaroslawhartman/withings-garmin-v2#5]
Hi,
I am trying to use this script but can't quite figure out how to have it to work.
After a bit of trial and error process i have managed to find out what my withings short name is however i am getting a persistent message:
user <SN> has not opened withings data
Is there a setting in my withings account that needs to be adjusted?
many thanks!

**Comment by dinde** [comment]
Hi,
I hitted the same issue.
I believe this issue is due to the new "Nokia/Withings" UI.
I edited sync.py and commented out lines 79, 80 and 81.

I'll pull request.
Cheers

**Comment by jaroslawhartman** [comment]
Merged fix from David @dinde
